### PR TITLE
merge wireguard package from LEDE

### LINKED ISSUE #55: Update Wireguard
The included version doesn't work with new versions anymore

### PR DESCRIPTION
**Pull request by anarcat**
wireguard is now in the base LEDE system

this is a port of https://github.com/lede-project/source/pull/1409

fixes #55

### CODE REVIEW

**Comment by anarcat** [comment]
an alternative to this would be to update the packages feed to https://github.com/openwrt/packages/commit/79ef85aa8c212586a0934fecc299205b8df66d01 - but since that includes a *lot* of other changes the Turris team may not want to vet one by one (and anyways, wireguard ends up being removed from "packages" in https://github.com/openwrt/packages/commit/ff07e0c83573eae5c1cc8e78ffaea18487fc04c5), it may be simpler to just do the right thing here...

**Comment by anarcat** [comment]
this was merged, thanks!

**Comment by anarcat** [comment]
oh, and do make sure you update the feeds so that there's no conflicting wireguard package there as well...

**Comment by ja-pa** [comment]
Thx for patch, right now it's in our test branch and it should be part of next release

**Comment by anarcat** [comment]
that's great - i assume you also updated the packages feeds as well?

**Pull request closed without merging**
